# Unique name for this workflow
name: PR name change
# Definition when the workflow should run
on: pull_request_target
permissions:
  pull-requests: write
  contents: write
jobs:
  pull-request-title-change:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: 'Read title'
        id: get-title
        #shell: bash
        run: |
          echo "${{ github.event.pull_request.title }}" >> $PR_TITLE
          echo "PR title"
          echo $PR_TITLE
          