# Unique name for this workflow
name: PR name change
# Definition when the workflow should run
on: 
  pull_request: #_target
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
jobs:
  pull-request-title-change:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: 'Read title'
        id: get-title
        #shell: bash
        env: 
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo $TITLE
          echo "PR title"
          echo "What is the $TITLE"
      - name: 'Split title'
        id: split-title
        env: 
          TITLE: ${{ github.event.pull_request.title }}
        if: |
          contains( ${{env.TITLE}}, ':') == 'true'
        run: echo "fragment=${TITLE##*:}" >> $GITHUB_OUTPUT
      # Another step
      - name: Test variable
        #env:
        #  TITLE_NEW:  ("deps(" + "packagename" + "):" + "${{ steps.split-title.outputs.fragment }}")
        run: |
          echo "Split Title is ${{ steps.split-title.outputs.fragment }}"
          part1="deps("
          part2="):"
          packagename="eslint"
          echo "part1 is $part1"
          echo "part2 is $part2"
          echo "packagename is $packagename"
          pr_title="$part1$packagename$part2${{ steps.split-title.outputs.fragment }}"
          echo "$pr_title"
        #echo "$title_new"
      # gh pr edit --title "$title_new"