# Unique name for this workflow
name: PR name change
# Definition when the workflow should run
on: 
  pull_request: #_target
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
jobs:
  pull-request-title-change:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: 'Read title'
        id: get-title
        #shell: bash
        env: 
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo $TITLE
          echo "PR title"
          echo "What is the $TITLE"
      - name: 'Split title'
        id: split-title
        env: 
          TITLE: ${{ github.event.pull_request.title }}
        if: |
          (contains( env.TITLE, ':') == 'true')
        run: echo "::set-output name=fragment::${TITLE##*:}"
      # Another step
      - name: Test variable
        run: |
          echo ${{ steps.split-title.outputs.fragment }}
          
          # echo "::set-output name=fragment::${BRANCH##*/}"
          # newTitle=$"{0}({1}):{2}"
          # readarray -d " " -t strarr <<< "$TITLE"
          # gh pr edit --title format($newTitle, ${strarr[0]}, ${strarr[1]}, ${strarr[2]})