# Unique name for this workflow
name: PR name change
# Definition when the workflow should run
on:
  pull_request: #_target
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
jobs:
  pull-request-title-change:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: 'Read title'
        id: get-title
        #shell: bash
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo $TITLE
          echo "PR title"
          echo "What is the $TITLE"
      - name: 'Split title'
        id: split-title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        if: |
          contains( ${{env.TITLE}}, ':')
        run: |
          echo "title_pt2=${env.TITLE##*:}" >> $GITHUB_OUTPUT
          echo "title_pt1=${env.TITLE//:/ }" >> $GITHUB_OUTPUT
      # Another step
      - name: Test variable
        #env:
        #  TITLE_NEW:  ("deps(" + "packagename" + "):" + "${{ steps.split-title.outputs.title_pt2 }}")
        env:
          #TITLE: ${{ github.event.pull_request.title }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{github.event.pull_request.html_url}}
        run: |
          echo "title_pt2=${env.TITLE##*:}" #>> $splitTitle
          echo "title_pt1=${env.TITLE//:/ }" #>> $prefix
          gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
          echo "Split Title is ${{ steps.split-title.outputs.title_pt1 }} ${{ steps.split-title.outputs.title_pt2 }}"
          part1="${{ steps.split-title.outputs.title_pt1 }}("
          packagename="eslint"
          part2="):${{ steps.split-title.outputs.title_pt2 }}"
          echo "part1 is $part1"
          echo "part2 is $part2"
          echo "packagename is $packagename"
          pr_title="$part1$packagename$part2"
          echo "$pr_title"
          gh pr edit "$PR_URL" --title "$pr_title"
