# Unique name for this workflow
name: PR Validation
# Definition when the workflow should run
on:
  workflow_dispatch:
  #pull_request:
  #  types: [edited, opened, synchronize, reopened, review_requested]
  #  paths:
  #    - 'force-app/**'
  #    - 'pmd/**'
  #    - 'package.json'

# Jobs to be executed
jobs:
  format-lint-lwc-tests:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      # Install Volta to enforce proper node and package manager versions
      - name: 'Install Volta'
        uses: volta-cli/action@v4

      # Cache node_modules to speed up the process
      - name: 'Restore node_modules cache'
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ env.cache-name }}-
            npm-
      # Install npm dependencies for Prettier and Jest
      - name: 'Install npm dependencies'
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      # Prettier formatting
      - name: 'Code formatting verification with Prettier'
        run: npm run prettier:verify:apex

      # Lint LWC / Aura
      - name: 'Lint Lightning Web Components / Aura Components'
        run: npm run lint

      # LWC unit tests
      - name: 'Unit test Lightning Web Components'
        run: npm run test:unit:coverage

      # Upload code coverage data
      - name: 'Upload code coverage for LWC to Codecov.io'
        uses: codecov/codecov-action@v3
        with:
          flags: LWC

  scan-pmd-action:
    runs-on: ubuntu-latest
    needs: format-lint-lwc-tests
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      - name: 'Setup java'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      # Run PMD scan
      - name: 'Perform PMD scan with PMD action'
        uses: pmd/pmd-github-action@v1
        with:
          version: 'latest'
          sourcePath: 'force-app'
          rulesets: 'pmd/deployRules.xml'
          analyzeModifiedFilesOnly: 'false'
          createGitHubAnnotations: 'true'
      # Check for PMD violations
      - name: 'Check for PMD violations'
        if: steps.pmd.outputs.violations != 0
        run: exit 1

  scratch-org-apex-tests:
    runs-on: ubuntu-latest
    needs: format-lint-lwc-tests
    if: ${{ github.actor != 'dependabot[bot]'}}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          npm install sfdx-cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sfdx --version
      # Store secret for dev hub
      - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
        shell: bash
        run: |
          echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
          secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
          if [ $secretFileSize == 1 ]; then
              echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
              exit 1;
          fi
      # Authenticate dev hub
      - name: 'Authenticate Dev Hub'
        run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d

      # Add namespace to project config
      - name: Add namespace to project config
        run: |
          sed -i 's,"namespace": "","namespace": "",' sfdx-project.json

      # Create scratch org
      - name: 'Create scratch org'
        run: sfdx force:org:create -f config/project-scratch-def.json -a ChangeMe -s -d 1 -w 20 --noancestors

      # Deploy source to scratch org
      - name: 'Push source to scratch org'
        run: sfdx force:source:push

      # Assign permissionset
      #- name: 'Assign permissionset to default user'
      #  run: sfdx force:user:permset:assign -n My_Permission_Set

      # Import sample data
      - name: 'Import sample data'
        run: sfdx force:data:tree:import -p ./data/data-plan.json

      # Run Apex tests in scratch org
      - name: 'Run Apex tests'
        run: sfdx force:apex:test:run -c -r human -l RunLocalTests -d ./tests/apex -w 20

      # Delete temporary test file that Codecov is unable to parse
      - name: 'Delete coverage file (temporary step)'
        run: rm ./tests/apex/test-result-707*-codecoverage.json

      # Upload code coverage data
      - name: 'Upload code coverage for Apex to Codecov.io'
        uses: codecov/codecov-action@v3
        with:
          flags: Apex

      # Housekeeping
      - name: 'Delete scratch org'
        if: always()
        run: sfdx force:org:delete -p -u ChangeMe

  sfdx-scanner:
    runs-on: ubuntu-latest
    needs: format-lint-lwc-tests
    if: ${{ github.actor != 'dependabot[bot]'  && 1 == 2 }}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run plugins:install @salesforce/sfdx-scanner
      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.7
        with:
          pmdconfig: 'pmd/deployRules.xml'
          severity-threshold: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
